// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ESFA.UI.Specflow.Framework.FindACourse.Project.Tests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Find A Course")]
    public partial class FindACourseFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "FindACourse.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Find A Course", "\tAs a user\r\n\tI am able to access and use the Find a Course Page", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("DFC-3885 Select Location and Distance")]
        [NUnit.Framework.CategoryAttribute("DFC-3885")]
        [NUnit.Framework.TestCaseAttribute("Chemistry", "b13 9da", "1 Mile", null)]
        [NUnit.Framework.TestCaseAttribute("Bricklaying", "B13 9DA", "3 Miles", null)]
        [NUnit.Framework.TestCaseAttribute("Maths", "London", "5 Miles", null)]
        [NUnit.Framework.TestCaseAttribute("English", "Birmingham", "10 Miles", null)]
        [NUnit.Framework.TestCaseAttribute("Plumbing", "London", "15 Miles", null)]
        [NUnit.Framework.TestCaseAttribute("Electronic", "London", "20 Miles", null)]
        [NUnit.Framework.TestCaseAttribute("Medicine", "Birmingham", "National", null)]
        public virtual void DFC_3885SelectLocationAndDistance(string courseName, string location, string distance, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "DFC-3885"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("DFC-3885 Select Location and Distance", null, @__tags);
#line 6
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 7
  testRunner.Given("I navigate to Find a Course home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
  testRunner.When(string.Format("I enter course {0}", courseName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 9
  testRunner.And(string.Format("I enter location {0}", location), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
  testRunner.And(string.Format("I select distance {0}", distance), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("DFC-4090 Search for Courses By Location & Distance")]
        [NUnit.Framework.CategoryAttribute("DFC-4090")]
        [NUnit.Framework.TestCaseAttribute("Chemistry", "b13 9da", "1 Mile", null)]
        [NUnit.Framework.TestCaseAttribute("Bricklaying", "B13 9DA", "3 Miles", null)]
        [NUnit.Framework.TestCaseAttribute("Maths", "London", "5 Miles", null)]
        [NUnit.Framework.TestCaseAttribute("English", "Birmingham", "10 Miles", null)]
        [NUnit.Framework.TestCaseAttribute("Plumbing", "London", "15 Miles", null)]
        [NUnit.Framework.TestCaseAttribute("Electronic", "London", "20 Miles", null)]
        [NUnit.Framework.TestCaseAttribute("Medicine", "Birmingham", "National", null)]
        public virtual void DFC_4090SearchForCoursesByLocationDistance(string courseName, string location, string distance, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "DFC-4090"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("DFC-4090 Search for Courses By Location & Distance", null, @__tags);
#line 25
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 26
  testRunner.Given("I navigate to Find a Course home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 27
  testRunner.When(string.Format("I enter course {0}", courseName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 28
  testRunner.And(string.Format("I enter location {0}", location), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 29
  testRunner.And(string.Format("I select distance {0}", distance), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 30
  testRunner.And("I click Search", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 31
  testRunner.Then("I should be on Search Results for page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("DFC-4090 Search for Courses By Location & Distance Invalid Location")]
        [NUnit.Framework.CategoryAttribute("DFC-4090")]
        [NUnit.Framework.TestCaseAttribute("Chemistry", "honalulu", "1 Mile", null)]
        [NUnit.Framework.TestCaseAttribute("Bricklaying", "x99 9xx", "3 Miles", null)]
        [NUnit.Framework.TestCaseAttribute("Maths", "davy st, edinburgh", "5 Miles", null)]
        [NUnit.Framework.TestCaseAttribute("English", "xxxxxxxxx", "10 Miles", null)]
        [NUnit.Framework.TestCaseAttribute("Plumbing", "wherever", "15 Miles", null)]
        [NUnit.Framework.TestCaseAttribute("Electronic", "anywhere", "20 Miles", null)]
        [NUnit.Framework.TestCaseAttribute("Medicine", "nowhere", "National", null)]
        public virtual void DFC_4090SearchForCoursesByLocationDistanceInvalidLocation(string courseName, string location, string distance, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "DFC-4090"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("DFC-4090 Search for Courses By Location & Distance Invalid Location", null, @__tags);
#line 46
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 47
  testRunner.Given("I navigate to Find a Course home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 48
  testRunner.When(string.Format("I enter course {0}", courseName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 49
  testRunner.And(string.Format("I enter location {0}", location), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 50
  testRunner.And(string.Format("I select distance {0}", distance), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 51
  testRunner.And("I click Search", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 52
  testRunner.Then("I should be on Search Results for page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 53
  testRunner.And("no results found message is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("DFC-4090 Search for Courses By Location & Distance Null Results")]
        [NUnit.Framework.CategoryAttribute("DFC-4090")]
        [NUnit.Framework.TestCaseAttribute("ARCHAEOLOGIST", "PO30 1DN", "1 Mile", null)]
        public virtual void DFC_4090SearchForCoursesByLocationDistanceNullResults(string courseName, string location, string distance, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "DFC-4090"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("DFC-4090 Search for Courses By Location & Distance Null Results", null, @__tags);
#line 68
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 69
  testRunner.Given("I navigate to Find a Course home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 70
  testRunner.When(string.Format("I enter course {0}", courseName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 71
  testRunner.And(string.Format("I enter location {0}", location), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 72
  testRunner.And(string.Format("I select distance {0}", distance), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 73
  testRunner.And("I click Search", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 74
  testRunner.Then("I should be on Search Results for page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 75
  testRunner.And("no results found message is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("DFC-3884 Select Qualification Level")]
        [NUnit.Framework.CategoryAttribute("DFC-3884")]
        [NUnit.Framework.TestCaseAttribute("Chemistry", "Entry level - Skills for Life", null)]
        [NUnit.Framework.TestCaseAttribute("Bricklaying", "Level 1 - First certificate", null)]
        [NUnit.Framework.TestCaseAttribute("Maths", "Level 2 - GCSE/O level", null)]
        [NUnit.Framework.TestCaseAttribute("English", "Level 3 - A level/Access to higher education diploma", null)]
        [NUnit.Framework.TestCaseAttribute("Plumbing", "Level 4 - Certificate of higher education/HNC", null)]
        [NUnit.Framework.TestCaseAttribute("Electronic", "Level 5 - Foundation degree/HND", null)]
        [NUnit.Framework.TestCaseAttribute("Medicine", "Level 6 - Degree/Graduate diploma", null)]
        [NUnit.Framework.TestCaseAttribute("Biology", "Level 7 - Masters Degree/Postgraduate diploma", null)]
        [NUnit.Framework.TestCaseAttribute("Physics", "Level 8 - Doctorate/PhD", null)]
        public virtual void DFC_3884SelectQualificationLevel(string courseName, string qualificationLevel, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "DFC-3884"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("DFC-3884 Select Qualification Level", null, @__tags);
#line 84
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 85
  testRunner.Given("I navigate to Find a Course home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 86
  testRunner.When(string.Format("I enter course {0}", courseName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 87
  testRunner.And(string.Format("I select qualification {0}", qualificationLevel), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("DFC-3884 Select Qualification Level Default Value")]
        [NUnit.Framework.CategoryAttribute("DFC-3884")]
        [NUnit.Framework.TestCaseAttribute("Chemistry", "Entry level - Skills for Life", null)]
        public virtual void DFC_3884SelectQualificationLevelDefaultValue(string courseName, string qualificationLevel, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "DFC-3884"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("DFC-3884 Select Qualification Level Default Value", null, @__tags);
#line 104
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 105
  testRunner.Given("I navigate to Find a Course home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 106
  testRunner.When(string.Format("I enter course {0}", courseName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 107
  testRunner.And("Qualification Level field displays default Select level", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("DFC-4091 Search for Courses By Qualification Level")]
        [NUnit.Framework.CategoryAttribute("DFC-4091")]
        [NUnit.Framework.TestCaseAttribute("Chemistry", "Entry level - Skills for Life", null)]
        [NUnit.Framework.TestCaseAttribute("Bricklaying", "Level 1 - First certificate", null)]
        [NUnit.Framework.TestCaseAttribute("Maths", "Level 2 - GCSE/O level", null)]
        [NUnit.Framework.TestCaseAttribute("English", "Level 3 - A level/Access to higher education diploma", null)]
        [NUnit.Framework.TestCaseAttribute("Plumbing", "Level 4 - Certificate of higher education/HNC", null)]
        [NUnit.Framework.TestCaseAttribute("Electronic", "Level 5 - Foundation degree/HND", null)]
        [NUnit.Framework.TestCaseAttribute("Medicine", "Level 6 - Degree/Graduate diploma", null)]
        [NUnit.Framework.TestCaseAttribute("Biology", "Level 7 - Masters Degree/Postgraduate diploma", null)]
        [NUnit.Framework.TestCaseAttribute("Physics", "Level 8 - Doctorate/PhD", null)]
        public virtual void DFC_4091SearchForCoursesByQualificationLevel(string courseName, string qualificationLevel, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "DFC-4091"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("DFC-4091 Search for Courses By Qualification Level", null, @__tags);
#line 116
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 117
  testRunner.Given("I navigate to Find a Course home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 118
  testRunner.When(string.Format("I enter course {0}", courseName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 119
  testRunner.And(string.Format("I select qualification {0}", qualificationLevel), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 120
  testRunner.And("I click Search", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 121
  testRunner.Then("I should be on Search Results for page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("DFC-4091 Search for Courses By Qualification Level Null Results")]
        [NUnit.Framework.CategoryAttribute("DFC-4091")]
        [NUnit.Framework.TestCaseAttribute("ARCHEOLOGY", "Entry level - Skills for Life", null)]
        public virtual void DFC_4091SearchForCoursesByQualificationLevelNullResults(string courseName, string qualificationLevel, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "DFC-4091"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("DFC-4091 Search for Courses By Qualification Level Null Results", null, @__tags);
#line 138
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 139
  testRunner.Given("I navigate to Find a Course home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 140
  testRunner.When(string.Format("I enter course {0}", courseName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 141
  testRunner.And(string.Format("I select qualification {0}", qualificationLevel), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 142
  testRunner.And("I click Search", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 143
  testRunner.Then("I should be on Search Results for page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 144
  testRunner.And("no results found message is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("DFC-3888 Search for Courses By Course Name All Options")]
        [NUnit.Framework.CategoryAttribute("DFC-3888")]
        [NUnit.Framework.TestCaseAttribute("Chemistry", "Entry level - Skills for Life", "Birmingham", "1 Mile", null)]
        [NUnit.Framework.TestCaseAttribute("Bricklaying", "Level 1 - First certificate", "London", "3 Miles", null)]
        [NUnit.Framework.TestCaseAttribute("Maths", "Level 2 - GCSE/O level", "London", "5 Miles", null)]
        [NUnit.Framework.TestCaseAttribute("English", "Level 3 - A level/Access to higher education diploma", "Birmingham", "10 Miles", null)]
        [NUnit.Framework.TestCaseAttribute("Plumbing", "Level 4 - Certificate of higher education/HNC", "London", "15 Miles", null)]
        [NUnit.Framework.TestCaseAttribute("Electronic", "Level 5 - Foundation degree/HND", "London", "20 Miles", null)]
        [NUnit.Framework.TestCaseAttribute("Medicine", "Level 6 - Degree/Graduate diploma", "Birmingham", "National", null)]
        [NUnit.Framework.TestCaseAttribute("Biology", "Level 7 - Masters Degree/Postgraduate diploma", "London", "3 Miles", null)]
        [NUnit.Framework.TestCaseAttribute("Physics", "Level 8 - Doctorate/PhD", "London", "5 Miles", null)]
        public virtual void DFC_3888SearchForCoursesByCourseNameAllOptions(string courseName, string qualificationLevel, string location, string distance, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "DFC-3888"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("DFC-3888 Search for Courses By Course Name All Options", null, @__tags);
#line 153
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 154
  testRunner.Given("I navigate to Find a Course home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 155
  testRunner.When(string.Format("I enter course {0}", courseName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 156
  testRunner.And(string.Format("I select qualification {0}", qualificationLevel), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 157
  testRunner.And(string.Format("I enter location {0}", location), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 158
  testRunner.And(string.Format("I select distance {0}", distance), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 159
  testRunner.And("I click Search", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 160
  testRunner.Then("I should be on Search Results for page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("DFC-3888 Search for Courses By Course Name Only")]
        [NUnit.Framework.CategoryAttribute("DFC-3888")]
        [NUnit.Framework.TestCaseAttribute("Chemistry", null)]
        [NUnit.Framework.TestCaseAttribute("Bricklaying", null)]
        [NUnit.Framework.TestCaseAttribute("Maths", null)]
        [NUnit.Framework.TestCaseAttribute("English", null)]
        [NUnit.Framework.TestCaseAttribute("Plumbing", null)]
        [NUnit.Framework.TestCaseAttribute("Electronic", null)]
        [NUnit.Framework.TestCaseAttribute("Medicine", null)]
        [NUnit.Framework.TestCaseAttribute("Biology", null)]
        [NUnit.Framework.TestCaseAttribute("Physics", null)]
        public virtual void DFC_3888SearchForCoursesByCourseNameOnly(string courseName, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "DFC-3888"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("DFC-3888 Search for Courses By Course Name Only", null, @__tags);
#line 177
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 178
  testRunner.Given("I navigate to Find a Course home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 179
  testRunner.When(string.Format("I enter course {0}", courseName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 180
  testRunner.And("I click Search", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 181
  testRunner.Then("I should be on Search Results for page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("DFC-3888 Search for Courses By Course Name Null Results")]
        [NUnit.Framework.CategoryAttribute("DFC-3888")]
        [NUnit.Framework.TestCaseAttribute("bbbbbbbbb", null)]
        public virtual void DFC_3888SearchForCoursesByCourseNameNullResults(string courseName, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "DFC-3888"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("DFC-3888 Search for Courses By Course Name Null Results", null, @__tags);
#line 198
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 199
  testRunner.Given("I navigate to Find a Course home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 200
  testRunner.When(string.Format("I enter course {0}", courseName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 201
  testRunner.And("I click Search", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 202
  testRunner.Then("I should be on Search Results for page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 203
  testRunner.And("no results found message is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("DFC-3883 Auto Populate Course Name")]
        [NUnit.Framework.CategoryAttribute("DFC-3883")]
        [NUnit.Framework.TestCaseAttribute("team", "TEAM,TEAM BUILDING,TEAM WORK,TEAM WORKING,TEAMWORK,TEAMWORKING", null)]
        [NUnit.Framework.TestCaseAttribute("builder", "BUILDER,BUILDING,BUILDING MAINTENANCE,BUILDING SERVICES,BUILDING SERVICES ENGINEE" +
            "RING,BUILDING SURVEYING,CONSTRUCTION", null)]
        public virtual void DFC_3883AutoPopulateCourseName(string courseName, string autopopulateList, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "DFC-3883"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("DFC-3883 Auto Populate Course Name", null, @__tags);
#line 212
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 213
  testRunner.Given("I navigate to Find a Course home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 214
  testRunner.When(string.Format("one letter at a time {0}", courseName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 215
  testRunner.Then(string.Format("the Course suggestions {0} displayed", autopopulateList), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 216
  testRunner.And(string.Format("I Can select one of the List options {0}", courseName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 217
  testRunner.When("I click Search", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 218
  testRunner.Then("I should be on Search Results for page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("DFC-4094 Contact Adviser")]
        [NUnit.Framework.CategoryAttribute("DFC-4094")]
        public virtual void DFC_4094ContactAdviser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("DFC-4094 Contact Adviser", null, new string[] {
                        "DFC-4094"});
#line 228
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 229
  testRunner.Given("I navigate to Find a Course home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 230
  testRunner.When("I click Contact an adviser link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 231
  testRunner.Then("I will be on Contact us page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("DFC-3887 View Qualification Level Help Text")]
        [NUnit.Framework.CategoryAttribute("DFC-3887")]
        public virtual void DFC_3887ViewQualificationLevelHelpText()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("DFC-3887 View Qualification Level Help Text", null, new string[] {
                        "DFC-3887"});
#line 236
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 237
  testRunner.Given("I navigate to Find a Course home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 238
  testRunner.When("I click What qualification levels mean link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 239
  testRunner.Then("I will be on What qualification levels mean page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
